import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from '@/components/theme-provider';
import Header from '@/components/header';
import AppProvider from "@/app/AppProvider";
import {cookies} from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({subsets: ['vietnamese']});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children
                                         }: Readonly<{
    children: React.ReactNode
}>) {
    const cookieStore = await cookies();
    const sessionToken = cookieStore.get('sessionToken')?.value;
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <Header/>
            <AppProvider
                initSessionToken={sessionToken || ''}>
                {children}
            </AppProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
